nextflow run undercover-grna-pipeline -r main \
 --data_method_pair_file /home/stat/timbar/research_code/sceptre2-manuscript/param_files/data_method_pair_file.groovy \
 --result_dir /home/stat/timbar/data/projects/sceptre2/results/undercover_grna_analysis \
 --result_file_name undercover_result_grp_size_1.rds \
 --grna_modality assignment \
 --group_size 1 \
 --is_group_size_frac false \
 --partition_count 1 \
 --is_partition_count_frac true \
 --machine_name hpcc \
 --time 07151633 \
 -profile standard \
 -resume
