---
title: "Effective sample sizes"
author: "Tim"
date: "2022-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Here, I study the effective sample sizes across datasets, both on low and high MOI data.

```{r}
library(tidyverse)

result_dir <- paste0(.get_config_path("LOCAL_SCEPTRE2_DATA_DIR"), "results/")
sample_size_df <- readRDS(paste0(result_dir,
                                 "dataset_sample_sizes/n_nonzero_cells_per_grna.rds")) |>
  dplyr::mutate(dataset = dataset_concat,
                dataset_concat = NULL, paper = NULL, modality = NULL) |>
  dplyr::rename(grna_group = target, response_id = feature_id)
```

We compute the effective sample size across low MOI datasets, considering two cases: first, taking the control group to be the set of NT cells, and second, taking the control group to be the compliment set.

```{r}
# compute the NTC effective sample size df
ntc_effective_samp_size_df <- sample_size_df |>
  filter(grna_group == "non-targeting") |>
  group_by(response_id, dataset) |>
  summarize(ntc_effective_sample_size = sum(n_nonzero_cells))

# compute the grouped effective sample size df
sample_size_df_grouped <- sample_size_df |>
  group_by(response_id, dataset, grna_group) |>
  summarize(n_nonzero_cells = sum(n_nonzero_cells))

# join with the sample size df
sample_size_df <- left_join(x = sample_size_df,
                            y = ntc_effective_samp_size_df,
                            by = c("response_id", "dataset")) |>
  filter(grna_group != "non-targeting")

# compute the effective sample size for all trans tests of association
sample_size_df |>
  group_by(response_id, dataset, grna_group)
```

