---
title: 'Debugging sceptre pt 6: running sceptre without covariates'
author: "Tim"
date: "2022-10-29"
output: html_document
---

```{r, message=FALSE, error=FALSE, warning=FALSE, echo=FALSE}
library(katlabutils)
library(tidyverse)
result_dir <- paste0(.get_config_path("LOCAL_SCEPTRE2_DATA_DIR"), "results/")

# load results
# 1. sceptre (with covariates)
sceptre_res_cov <- readRDS(paste0(result_dir,
                                  "undercover_grna_analysis/undercover_result_grp_size_1_sceptre.rds")) |>
  select(-clock_time, -max_ram)

# 2. sceptre (without covariates)
sceptre_res_no_cov <- readRDS(paste0(result_dir,
                                     "undercover_grna_analysis/sceptre_debug_no_cov.rds"))
funct_script <- paste0(.get_config_path("LOCAL_CODE_DIR"), "sceptre2-manuscript/writeups/undercover_results_eda/analyze_undercover_results_plot_functs.R")

# 3. sceptre debug
sceptre_debug <- readRDS(paste0(result_dir,
                                    "undercover_grna_analysis/sceptre_debug.rds"))

source(funct_script)
```

```{r, message=FALSE, error=FALSE, warning=FALSE, echo=FALSE}
replace_slash_w_underscore <- function(df) {
  df |> dplyr::mutate(dataset = gsub(pattern = "/",
                                replacement = "_",
                                fixed = TRUE,
                                x = dataset))
}


sceptre_res_cov <- sceptre_res_cov |>
  replace_slash_w_underscore() |>
  mutate(covariates = factor("yes"))

sceptre_res_no_cov <- sceptre_res_no_cov |>
  replace_slash_w_underscore() |>
  mutate(covariates = factor("no"))

sceptre_res <- rbind(sceptre_res_cov, sceptre_res_no_cov)
rm(sceptre_res_cov, sceptre_res_no_cov)

ks_stat_categories <- list(good = c(0, 1e-2),
                           adequate = c(1e-2, 5e-2),
                           subpar = c(5e-2, 0.1),
                           poor = c(0.1, 1))
```

I study plot the SCEPTRE results with and without covariates.

```{r}
sceptre_res |>
  filter(dataset == "papalexi_eccite_screen_gene",
         undercover_grna != "NTg8") |>
  ggplot(mapping = aes(y = p_value, col = covariates)) +
   stat_qq_points(ymin = 1e-9, size = 0.8) +
   geom_abline(col = "darkred") +
   stat_qq_band() +
   theme_bw() +
   scale_x_continuous(trans = revlog_trans(10)) +
   scale_y_continuous(trans = revlog_trans(10)) +
   labs(x = "Expected quantile", y = "Observed quantile") +
   theme(legend.position = "bottom",
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         panel.background = element_blank())
```


```{r}
sceptre_res |>
  filter(dataset == "papalexi_eccite_screen_protein") |>
  ggplot(mapping = aes(y = p_value, col = covariates)) +
   stat_qq_points(ymin = 1e-9, size = 0.8) +
   geom_abline(col = "darkred") +
   stat_qq_band() +
   theme_bw() +
   scale_x_continuous(trans = revlog_trans(10)) +
   scale_y_continuous(trans = revlog_trans(10)) +
   labs(x = "Expected quantile", y = "Observed quantile") +
   theme(legend.position = "bottom",
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         panel.background = element_blank())
```

# Nonparametric density fitting

Can we obtain accurate p-values by instead fitting a nonparametric density to the null distribution? If so, how many resamples do we need?

```{r}
x <- sceptre_debug |>
  filter(dataset == "papalexi/eccite_screen/gene") |>
  sample_n(8) |>
  select(response_id, undercover_grna, p_value, ks_stat, p_value_emp)

f <- function(x, z_null, bw) {
  l_p <- mean(pnorm(x, z_null, bw))
  2 * min(l_p, 1 - l_p)
}

i <- 1
response_id <- x[i, "response_id"] |> as.character()
undercover_grna <- x[i, "undercover_grna"] |> as.character()
sceptre_args <- lowmoi:::get_sceptre_function_args_for_pair(
  response_id = response_id, undercover_grna = undercover_grna,
  dataset_name = "papalexi/eccite_screen/gene", output_amount = 3, B = 100000)

out <- do.call(what = sceptre2::run_sceptre_low_moi, args = sceptre_args)
z_null <- out |>
  select(starts_with("z_null_")) |>
  as.numeric()
z_star <- out$z_value
hist(z_null, breaks = 50)
abline(v = z_star, col = "blue")
n_samp <- 10000
z_null_samp <- sample(z_null, replace = FALSE, size = n_samp)
bw <- bw.SJ(x = z_null_samp)

p_kde <- f(z_star, z_null_samp, bw)
p_emp <- sceptre2:::compute_empirical_p_value(z_star, z_null, "both")
p_sn <- sceptre2:::compute_skew_normal_p_value(dp = sceptre2:::fit_skew_normal(z_null_samp)$dp,
                                               z_star = z_star, side = "both")

p_kde
p_emp
p_sn

p_emp/p_kde
p_emp/p_sn
```
