---
title: "Reproducing Schraivogel p-values"
author: "Gene"
date: "2023-04-12"
output: pdf_document
---

```{r}
# load packages
library(ondisc)
library(lowmoi)

###########
# LOAD ODMS
###########

################

LOCAL_SCEPTRE2_DATA_DIR <-.get_config_path("LOCAL_SCEPTRE2_DATA_DIR")
schraivogel_chr8_dir <- paste0(LOCAL_SCEPTRE2_DATA_DIR,
                               "data/schraivogel/enhancer_screen_chr8/")

# response info
response_odm_fp <- paste0(schraivogel_chr8_dir, "gene/matrix.odm")
response_metadata_fp <- paste0(schraivogel_chr8_dir, "gene/metadata_qc.rds")
response_odm <- read_odm(odm_fp = response_odm_fp, metadata_fp = response_metadata_fp)

# grna info
grna_odm_fp <- paste0(schraivogel_chr8_dir, "grna_expression/matrix.odm")
grna_metadata_fp <- paste0(schraivogel_chr8_dir, "grna_expression/metadata_qc.rds")
grna_odm <- read_odm(odm_fp = grna_odm_fp, metadata_fp = grna_metadata_fp)

################

schraivogel_dir <- .get_config_path("LOCAL_SCHRAIVOGEL_2020_DATA_DIR")
schraivogel_chr8_dir <- paste0(schraivogel_dir,
                               "processed/enhancer_screen_chr8/")

# response info
response_odm_fp <- paste0(schraivogel_chr8_dir, "gene/expression_matrix.odm")
response_metadata_fp <- paste0(schraivogel_chr8_dir, "gene/metadata.rds")
response_odm <- read_odm(odm_fp = response_odm_fp, metadata_fp = response_metadata_fp)

# grna info
grna_odm_fp <- paste0(schraivogel_chr8_dir, "grna_expression/raw_ungrouped.odm")
grna_metadata_fp <- paste0(schraivogel_chr8_dir, "grna_expression/raw_ungrouped_metadata.rds")
grna_odm <- read_odm(odm_fp = grna_odm_fp, metadata_fp = grna_metadata_fp)


###################################
# LOAD ORIGINAL SCHRAIVOGEL RESULT
###################################
orig_schraivogel_res <- readRDS(paste0(schraivogel_chr8_result_dir, "schraivogel_schraivogel_chr_8_results.rds"))
pairs_to_analyze <- data.frame(response_id = "PTDSS1",
                               grna_group = "chr8:97842054-97842529")

schraivogel_res_tim <- schraivogel_method(response_odm = response_odm,
                                          grna_odm = grna_odm,
                                          response_grna_group_pairs = pairs_to_analyze)
schraivogel_res_tim

orig_schraivogel_res |> dplyr::filter(response_id == pairs_to_analyze$response_id,
                                      grna_group == pairs_to_analyze$grna_group)
```
```{r}
LOCAL_SCHRAIVOGEL_DATA_DIR <-.get_config_path("LOCAL_SCHRAIVOGEL_2020_DATA_DIR")
replace_periods <- function(str){
  stringr::str_replace(stringr::str_replace(str, "[.]", ":"), "[.]", "-")
}
add_suffixes <- function(str){
  ifelse(str %in% c("CCNE2", "CPQ", "DSCC1", "FAM83A", "LRRCC1",
                    "OXR1", "PHF20L1", "RIPK2", "STK3", "UBR5"),
         paste0(str, "-TSS"),
         ifelse(str %in% c("GATA1", "HS2", "MYC", "ZFPM2"),
                paste0(str, "-enh"),
                str))
}
schraivogel_results_fp <- paste0(LOCAL_SCHRAIVOGEL_DATA_DIR,
                                 "raw/ftp/diff_expr_screen_nGenesCovar.csv")
schraivogel_results <- read_csv(schraivogel_results_fp) |>
  filter(sample == "8iScreen1",
         gene %in% get_feature_ids(gene_odm)) |> # genes that passed our QC
  mutate(grna_group = add_suffixes(replace_periods(perturbation))) |>
  rename(response_id = gene) |>
  select(response_id, grna_group, pvalue, logFC)
schraivogel_results |> 
  filter(response_id == "PTDSS1",
         grna_group == "chr8:97842054-97842529")

```