---
title: "SCEPTRE vs Seurat STAT3"
output: pdf_document
date: "2023-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages.
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(scales)
library(dplyr)
library(reshape2)
library(mixtools)
library(stringr)
library(enrichR)
library(kableExtra)
library(varhandle)
```


```{r}
#using absolute paths to download results since files exist on github
code_dir = .get_config_path("LOCAL_CODE_DIR")
data.dir = paste0(code_dir,"/sceptre2-manuscript/writeups/papalexi_analysis/")
sceptre_path = paste0(data.dir,
                  'sceptre_full_mrna_results_with_effect_size.rds')
seurat_path = paste0(data.dir,
                   'seurat_all_perturbations_results.rds')

sceptre = readRDS(sceptre_path)
seurat = readRDS(seurat_path)
```



```{r}
#get significant genes
seurat_etv7_sig = rownames(subset(seurat_etv7,p_val_adj < 0.1))
seurat_stat3_sig = rownames(subset(seurat_stat3,p_val_adj < 0.1))
seurat_nfkbia_sig = rownames(subset(seurat_nfkbia,p_val_adj < 0.1))
```
We see that Seurat-DE finds almost no significant genes after a bonferroni adjustment. \\

```{r}
#get number of response genes analyzed per perturbation
grna = unfactor(unique(sceptre$grna_group))
n = c()
for(val in grna){
  sceptre_stat3 = subset(sceptre,grna_group == val)
  sceptre_stat3$p_value_adj = p.adjust(sceptre_stat3$p_value,method = "BH")
  sceptre_stat3 = subset(sceptre_stat3,p_value_adj < 0.1)
  n = c(n,nrow(sceptre_stat3))
}

```

```{r}
summary_sceptre = data.frame(grna = grna, num_significant = n)
results = kable(summary_sceptre,booktabs = TRUE, linesep = "",
caption = "SCEPTRE: Number of Significant Genes vs Perturbation (FDR = 0.1)")
kable_styling(results,position = "center")
```

\newpage 

