---
title: "Mixscape Seurat DE"
output: pdf_document
date: "2023-02-21"
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Goal
The aim of this report is to replicate the results of Papalexi et al's pathway enrichment analysis.

```{r}
# Load packages.
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(scales)
#library(dplyr)
library(reshape2)
library(mixtools)
library(stringr)
library(enrichR)
library(kableExtra)
library(varhandle)
```

# Download Data
```{r}
# Download dataset using SeuratData.
options(timeout = 1000)
InstallData(ds = "thp1.eccite")

# Setup custom theme for plotting.
custom_theme <- theme(
  plot.title = element_text(size=16, hjust = 0.5),
  legend.key.size = unit(0.7, "cm"),
  legend.text = element_text(size = 14))

# Load object.
eccite <- LoadData(ds = "thp1.eccite")
```
# Normalize and plot UMAP
```{r}

# Normalize protein.
eccite <- NormalizeData(
  object = eccite,
  assay = "ADT",
  normalization.method = "CLR",
  margin = 2)


# Prepare RNA assay for dimensionality reduction:
# Normalize data, find variable features and scale data.
DefaultAssay(object = eccite) <- 'RNA'
eccite <- NormalizeData(object = eccite) %>% FindVariableFeatures() %>% ScaleData()

# Run Principle Component Analysis (PCA) to reduce the dimensionality of the data.
eccite <- RunPCA(object = eccite)

# Run Uniform Manifold Approximation and Projection (UMAP) to visualize clustering in 2-D.
eccite <- RunUMAP(object = eccite, dims = 1:40)

# Generate plots to check if clustering is driven by biological replicate ID,
# cell cycle phase or target gene class.
p1 <- DimPlot(
  object = eccite,
  group.by = 'replicate',
  label = F,
  pt.size = 0.2,
  reduction = "umap", cols = "Dark2", repel = T) +
  scale_color_brewer(palette = "Dark2") +
  ggtitle("Biological Replicate") +
  xlab("UMAP 1") +
  ylab("UMAP 2") +
  custom_theme

p2 <- DimPlot(
  object = eccite,
  group.by = 'Phase',
  label = F, pt.size = 0.2,
  reduction = "umap", repel = T) +
  ggtitle("Cell Cycle Phase") +
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  custom_theme

p3 <- DimPlot(
  object = eccite,
  group.by = 'crispr',
  pt.size = 0.2,
  reduction = "umap",
  split.by = "crispr",
  ncol = 1,
  cols = c("grey39","goldenrod3")) +
  ggtitle("Perturbation Status") +
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  custom_theme

# Visualize plots.
((p1 / p2 + plot_layout(guides = 'auto')) | p3 )
```

# Remove technical factors 
```{r}

# Calculate perturbation signature (PRTB).
eccite<- CalcPerturbSig(
  object = eccite,
  assay = "RNA",
  slot = "data",
  gd.class ="gene",
  nt.cell.class = "NT",
  reduction = "pca",
  ndims = 40,
  num.neighbors = 20,
  split.by = "replicate",
  new.assay.name = "PRTB")

# Prepare PRTB assay for dimensionality reduction:
# Normalize data, find variable features and center data.
DefaultAssay(object = eccite) <- 'PRTB'

# Use variable features from RNA assay.
VariableFeatures(object = eccite) <- VariableFeatures(object = eccite[["RNA"]])
eccite <- ScaleData(object = eccite, do.scale = F, do.center = T)

# Run PCA to reduce the dimensionality of the data.
eccite <- RunPCA(object = eccite, reduction.key = 'prtbpca', reduction.name = 'prtbpca')

# Run UMAP to visualize clustering in 2-D.
eccite <- RunUMAP(
  object = eccite,
  dims = 1:40,
  reduction = 'prtbpca',
  reduction.key = 'prtbumap',
  reduction.name = 'prtbumap')

# Generate plots to check if clustering is driven by biological replicate ID,
# cell cycle phase or target gene class.
q1 <- DimPlot(
  object = eccite,
  group.by = 'replicate',
  reduction = 'prtbumap',
  pt.size = 0.2, cols = "Dark2", label = F, repel = T) +
  scale_color_brewer(palette = "Dark2") +
  ggtitle("Biological Replicate") +
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  custom_theme

q2 <- DimPlot(
  object = eccite,
  group.by = 'Phase',
  reduction = 'prtbumap',
  pt.size = 0.2, label = F, repel = T) +
  ggtitle("Cell Cycle Phase") +
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  custom_theme

q3 <- DimPlot(
  object = eccite,
  group.by = 'crispr',
  reduction = 'prtbumap',
  split.by = "crispr",
  ncol = 1,
  pt.size = 0.2,
  cols = c("grey39","goldenrod3")) +
  ggtitle("Perturbation Status") +
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  custom_theme

# Visualize plots.
(q1 / q2 + plot_layout(guides = 'auto') | q3)

```


# Run mixscape 
```{r}
# Run mixscape.
eccite <- RunMixscape(
  object = eccite,
  assay = "PRTB",
  slot = "scale.data",
  labels = "gene",
  nt.class.name = "NT",
  min.de.genes = 5,
  iter.num = 10,
  de.assay = "RNA",
  verbose = F,
  prtb.type = "KO")

# Calculate percentage of KO cells for all target gene classes.
df <- prop.table(table(eccite$mixscape_class.global, eccite$NT),2)

df2 <- reshape2::melt(df)
df2$Var2 <- as.character(df2$Var2)
test <- df2[which(df2$Var1 == "KO"),]
test <- test[order(test$value, decreasing = T),]
new.levels <- test$Var2
df2$Var2 <- factor(df2$Var2, levels = new.levels )
df2$Var1 <- factor(df2$Var1, levels = c("NT", "NP", "KO"))
df2$gene <- sapply(as.character(df2$Var2), function(x) strsplit(x, split = "g")[[1]][1])
df2$guide_number <- sapply(as.character(df2$Var2),
                           function(x) strsplit(x, split = "g")[[1]][2])
df3 <- df2[-c(which(df2$gene == "NT")),]

p1 <- ggplot(df3, aes(x = guide_number, y = value*100, fill= Var1)) +
  geom_bar(stat= "identity") +
  theme_classic()+
  scale_fill_manual(values = c("grey49", "grey79","coral1")) +
  ylab("% of cells") +
  xlab("sgRNA")

p1 + theme(axis.text.x = element_text(size = 18, hjust = 1),
           axis.text.y = element_text(size = 18),
           axis.title = element_text(size = 16),
           strip.text = element_text(size=16, face = "bold")) +
  facet_wrap(vars(gene),ncol = 5, scales = "free") +
  labs(fill = "mixscape class") +theme(legend.title = element_text(size = 14),
                                       legend.text = element_text(size = 12))


```

# Perform Marker Gene Analysis/Pathway Enrichment Analysis Ordered by Log Fold Change

```{r}
eccite_copy = eccite
grna = unfactor((Idents(eccite)))
grna = substr(grna,1,nchar(grna)-3)
grna[nchar(grna)==0] = 'NT'
Idents(eccite_copy) = grna
prtb = unique(grna)[unique(grna) != 'NT']
#diff_genes <- vector(mode='list', length=length(prtb))
#names(diff_genes) = prtb
counter = 1
for(val in prtb){
  marker_all = FindMarkers(eccite_copy,ident.1 = val,ident.2 = 'NT',
                          assay = 'RNA',only.pos = F,base = exp(1),
                          logfc.threshold = 0,min.pct = 0)
  marker_all$grna = rep(val,nrow(marker_all))
  marker_all$response_id = rownames(marker_all)
  if(counter ==1){
    diff_genes = marker_all
  }else{
    diff_genes = rbind(diff_genes,marker_all)
  }
  counter = counter + 1
}
```


```{r}
sceptre2_dir <- .get_config_path("LOCAL_SCEPTRE2_DATA_DIR")
output_filename <- paste0(sceptre2_dir, "/results/papalexi_analysis/")
saveRDS(result_gene,paste0(output_filename,
                           "seurat_all_perturbations_results.rds"))
```





