---
title: "Perturbation propensity as a function of covariates"
author: "Gene"
date: '2022-06-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(katlabutils)
```

In this script we assess whether perturbation indicators are associated with any of the technical covariates.

First we read the results generated by `perturbation_propensity.R`:
```{r}
results_file <- paste0(
  .get_config_path("LOCAL_SCEPTRE2_DATA_DIR"),
  "results/perturbation_propensity_analysis/results.rds"
)
results <- readRDS(results_file)
results
```

Next, for each dataset, we plot the $p$-values for each covariate across NTCs:
```{r, echo = FALSE}
datasets <- results |>
  arrange(paper) |>
  pull(dataset) |>
  unique()
for (dataset in datasets) {
  results_dataset <- results |> filter(dataset == !!dataset)
  paper <- results_dataset |>
    pull(paper) |>
    unique()
  p_hist_joint <- results_dataset |>
    filter(test_type == "joint") |>
    ggplot(aes(x = pvalue)) +
    geom_histogram(colour = "black", binwidth = 0.1, boundary = 0) +
    facet_wrap(~covariate, scales = "free") +
    scale_x_continuous(limits = c(0, 1)) +
    labs(title = sprintf("%s %s (joint analysis)", paper, dataset)) +
    theme_bw()
  plot(p_hist_joint)

  p_qq_joint <- results_dataset |>
    filter(test_type == "joint") |>
    ggplot(aes(y = pvalue)) +
    stat_qq_points() +
    stat_qq_band() +
    geom_abline() +
    facet_wrap(~covariate, scales = "free") +
    scale_x_continuous(trans = revlog_trans(base = 10)) +
    scale_y_continuous(trans = revlog_trans(base = 10)) +
    labs(title = sprintf("%s %s (joint analysis)", paper, dataset)) +
    theme_bw()
  plot(p_qq_joint)

  p_hist_marginal <- results_dataset |>
    filter(test_type == "marginal") |>
    ggplot(aes(x = pvalue)) +
    geom_histogram(colour = "black", binwidth = 0.1, boundary = 0) +
    facet_wrap(~covariate, scales = "free") +
    scale_x_continuous(limits = c(0, 1)) +
    labs(title = sprintf("%s %s (marginal analysis)", paper, dataset)) +
    theme_bw()
  plot(p_hist_marginal)

  p_qq_marginal <- results_dataset |>
    filter(test_type == "marginal") |>
    ggplot(aes(y = pvalue)) +
    stat_qq_points() +
    stat_qq_band() +
    geom_abline() +
    facet_wrap(~covariate, scales = "free") +
    scale_x_continuous(trans = revlog_trans(base = 10)) +
    scale_y_continuous(trans = revlog_trans(base = 10)) +
    labs(title = sprintf("%s %s (marginal analysis)", paper, dataset)) +
    theme_bw()
  plot(p_qq_marginal)
}
```

```{r, eval = FALSE, echo = FALSE}
paper <- "papalexi"
dataset <- "eccite_screen"
paper <- "frangieh"
dataset <- "control"
paper <- "schraivogel"
dataset <- "enhancer_screen_chr11"

paper <- "schraivogel"
dataset <- "ground_truth_perturbseq"


# get gRNA ODM
grna_fp <- paste0(paper, "/", dataset, "/grna_assignment")
grna_odm <- lowmoi::load_dataset_modality(data_fp = grna_fp)

# get response ODM
response_fp <- paste0(paper, "/", dataset, "/gene")
response_odm <- lowmoi::load_dataset_modality(data_fp = response_fp)

# get list of NTC gRNAs
ntcs <- grna_odm |>
  get_feature_covariates() |>
  filter(target %in% c("non-targeting", "NT")) |>
  rownames() |>
  unique()

# get the gRNA assigned to each cell
assigned_grnas_df <- grna_odm |>
  get_cell_covariates() |>
  select(assigned_gRNA)

# get a logical vector of whether a cell was assigned an NTC
ntc_cells <- assigned_grnas_df |>
  mutate(ntc = assigned_gRNA %in% ntcs) |>
  pull(ntc)

# restrict assigned gRNAs to cells with an NTC
assigned_grnas <- assigned_grnas_df[ntc_cells, , drop = F] |> pull(assigned_gRNA)

# extract cell covariates from gene ODM, and restrict attention to cells with NTC
cell_covariates <- response_odm[, ntc_cells] |> get_cell_covariates()

# append assigned_grnas column to cell_covariates
df <- cell_covariates |>
  mutate(assigned_grna = assigned_grnas)
```
