---
title: "Power_exploration_mom"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data (negative control)

```{r, warning = FALSE, error = FALSE, message = FALSE}
library(eva)
library(tidyverse)
library(katlabutils)
library(cowplot)

conflicts_prefer(dplyr::rename)

sceptre2_results_dir <- paste0(.get_config_path("LOCAL_SCEPTRE2_DATA_DIR"), "results/")
# load empirical distributions
resampling_dists <- readRDS(paste0(sceptre2_results_dir, "resampling_distributions/sceptre_resampling_dists.rds"))
resampling_dists[1:5, 1:6]

# mom fit
mom_fit <- function(y){
    n <- length(y)    
    # maximum value gamma can take
    max.gamma1 <- 0.5*(4-pi)*(2/(pi-2))^1.5 - (.Machine$double.eps)^(1/4)    
    # method of moments strategy
    s <- sd(y)
    gamma1 <- sum((y-mean(y))^3)/(n*s^3)
    if(abs(gamma1) > max.gamma1) gamma1 <- sign(gamma1)*0.9*max.gamma1
    cp1 <- as.numeric(c(mean(y), s, gamma1))
    dp1 <- cp2dp(cp1, family="SN")
    return(dp1)
}
```


# Load data (negative control)
```{r, warning = FALSE, error = FALSE, message = FALSE}
library(sn)
# number of total sample
n <- 5e5

param_nc <- read_csv("figures/power_exploration/sknorm_tail_prob_500000_resamples_0.96_percentile/mom_param.csv")
param_twosides <- t(param_nc[,-1])
overshoot_ratio <- as.numeric(param_twosides[, 6])
undershoot_ratio <- as.numeric(param_twosides[, 7])
quantile_list <- seq(0.03, 0.97, length.out = 10)
tail_list <- (10:(0.04*n)) / n


# fix number of sample
no_sam <- round(exp(seq(log(1e3), log(5e4), length.out = 10)))[5]
set.seed(1)
overshoot_joint_fit <- list()
overshoot_joint_power <- list()
undershoot_joint_fit <- list()
undershoot_joint_power <- list()
tail_choice <- c("left", "right")
downsample_tail <- (10:(round(0.04*no_sam))) / no_sam
overshoot_left_fit <- data.frame(replicate_id = 1:330,
                                   overshoot_ratio = numeric(330),
                                   subsample = rep(no_sam, each = 330))
overshoot_left_power <- data.frame(replicate_id = 1:330,
                                   overshoot_ratio = numeric(330),
                                   subsample = rep(no_sam, each = 330))
undershoot_left_fit <- data.frame(replicate_id = 1:330,
                                   overshoot_ratio = numeric(330),
                                   subsample = rep(no_sam, each = 330))
undershoot_left_power <- data.frame(replicate_id = 1:330,
                                   overshoot_ratio = numeric(330),
                                   subsample = rep(no_sam, each = 330))
  
overshoot_right_fit <- data.frame(replicate_id = 1:330,
                                   overshoot_ratio = numeric(330),
                                   subsample = rep(no_sam, each = 330))
overshoot_right_power <- data.frame(replicate_id = 1:330,
                                   overshoot_ratio = numeric(330),
                                   subsample = rep(no_sam, each = 330))
undershoot_right_fit <- data.frame(replicate_id = 1:330,
                                   overshoot_ratio = numeric(330),
                                   subsample = rep(no_sam, each = 330))
undershoot_right_power <- data.frame(replicate_id = 1:330,
                                   overshoot_ratio = numeric(330),
                                   subsample = rep(no_sam, each = 330))
for (s in 1:330) {
  over_quantile_left_emp <- quantile(as.numeric(resampling_dists[s, 5:(4 + n)]), tail_list)
  under_quantile_left_emp <- quantile(as.numeric(resampling_dists[s, 5:(4 + n)]), tail_list)
  over_quantile_right_emp <- quantile(as.numeric(resampling_dists[s, 5:(4 + n)]), 1 - tail_list)
  under_quantile_right_emp <- quantile(as.numeric(resampling_dists[s, 5:(4 + n)]), 1 - tail_list)
  
  rd_set <- sample(1:5e5, no_sam)
  over_sub_sam <- as.numeric(resampling_dists[s, 4 + rd_set])
  under_sub_sam <- as.numeric(resampling_dists[s, 4 + rd_set])
  over_dp_fit <- mom_fit(over_sub_sam)
  under_dp_fit <- mom_fit(under_sub_sam)
  
  # undershoot left case for fit and power
  undershoot_left_fit[s, 2] <- max(tail_list / (psn(under_quantile_left_emp, dp = under_dp_fit)))
  under_quantile_emp_power <- quantile(as.numeric(under_sub_sam), downsample_tail)
  undershoot_left_power[s, 2] <- max(downsample_tail / (psn(under_quantile_emp_power, dp = under_dp_fit)))
      
  # overshoot left case for fit and power
  overshoot_left_fit[s, 2] <- max((psn(over_quantile_left_emp, dp = over_dp_fit)) / tail_list)
  over_quantile_emp_power <- quantile(as.numeric(over_sub_sam), downsample_tail)
  overshoot_left_power[s, 2] <- max((psn(over_quantile_emp_power, dp = over_dp_fit)) / downsample_tail)
          
  # undershoot right case for fit and power
  undershoot_right_fit[s, 2] <- max(tail_list / (1 - psn(under_quantile_right_emp, dp = under_dp_fit)))
  under_quantile_emp_power <- quantile(as.numeric(under_sub_sam), 1 - downsample_tail)
  undershoot_right_power[s, 2] <- max(downsample_tail / (1 - psn(under_quantile_emp_power, dp = under_dp_fit)))
      
  # overshoot right case for fit and power
  overshoot_right_fit[s, 2] <- max((1 - psn(over_quantile_right_emp, dp = over_dp_fit)) / tail_list)
  over_quantile_emp_power <- quantile(as.numeric(over_sub_sam), 1 - downsample_tail)
  overshoot_right_power[s, 2] <- max((1 - psn(over_quantile_emp_power, dp = over_dp_fit)) / downsample_tail)
  print(s)
}

# save file
write.csv(cbind(overshoot_left_fit, overshoot_right_fit), "overshoot_full_fit.csv")
write.csv(cbind(overshoot_left_power, overshoot_right_power), "overshoot_full_power.csv")
write.csv(cbind(undershoot_left_fit, undershoot_right_fit), "undershoot_full_fit.csv")
write.csv(cbind(undershoot_left_power, undershoot_right_power), "undershoot_full_power.csv")


full_results_overshoot <- bind_rows(
  overshoot_left_fit |> mutate(tail = "left", evaluation = "ground truth"),
  overshoot_right_fit |> mutate(tail = "right", evaluation = "ground truth"),
  overshoot_left_power |> mutate(tail = "left", evaluation = "estimate"),
  overshoot_right_power |> mutate(tail = "right", evaluation = "estimate")
) |>
  rename(ratio = overshoot_ratio) |>
  mutate(error_type = "overshoot")

full_results_undershoot <- bind_rows(
  undershoot_left_fit |> mutate(tail = "left", evaluation = "ground truth") |> rename(undershoot_ratio = overshoot_ratio),
  undershoot_right_fit |> mutate(tail = "right", evaluation = "ground truth", replicate_id = row_number(), subsample = 5690),
  undershoot_left_power |> mutate(tail = "left", evaluation = "estimate") |> rename(undershoot_ratio = overshoot_ratio),
  undershoot_right_power |> mutate(tail = "right", evaluation = "estimate") |> rename(undershoot_ratio = overshoot_ratio)
) |>
  rename(ratio = undershoot_ratio) |>
  mutate(error_type = "undershoot")

full_results <- bind_rows(
  full_results_overshoot,
  full_results_undershoot
) |>
  rename(id = replicate_id,
         num_samples_fit = subsample) |>
  as_tibble()

saveRDS(full_results, "full_nc_results.rds")
```
